### PR TITLE
[Submission] Cantisani, Ozerov, Essid, Richard

### PR DESCRIPTION
**Pull request by giorgiacantisani**
**AUTHOR**

Dear mdx workshop committee,

I request a review for the following MDX submission:

### **Title: User-Guided One-Shot Deep Model Adaptation for Music Source Separation**  

**Author(s): Giorgia Cantisani, Alexey Ozerov, Slim Essid, Gaël Richard**  

**Category ***

* [ ] `POSTERS` _(+Abstract: 250 Words+one page pdf)_
  > As a participant of the MDX challenge, please know that your poster would be automatically accepted after a minimal prescreening. Hence, don't forget to provide us with the link to your team in the AIcrowd website.
  > You are also welcome to submit us some unrelated abstract, in case your interest would be in presenting some method or idea you would just like to discuss with the participants passing by.  
  > => You *don't* need to include your poster in the PR. Just be ready to have it for D-day and show it to the audience through screen sharing.
* [x] `LONG TALK`
  > A long talk will last about 20-30min, including questions. This can be about some recent paper you published, or may also present some original research and investigations you did. If you pick this category, please provide us with an extended abstract of the talk, or directly with the slides if you have them available, even in an unfinished state, at your convenience. 
* [ ] `DISCUSSIONS`
  > This category is intended to stimulate fruitful discussions and collaborations. If you pick it, it means you are willing to chair some open discussion with the participants, mainly around one particular aspect of music demixing research. For that purpose, you should provide a minimal abstract as well as a list of a few questions you would like the participants to discuss about. Don't hesitate to propose ideas, We will possibly contact you in case we identify several similar topics that were proposed!

**Preferred Timezone***

* [x] A 11:00 PM (PDT) to 9:00 AM PDT
* [ ] B 11:00 AM (PDT) to 9:00 PM PDT

  > The preferred timezone will help us to organize the day schedule. You should select at least one, but can perfectly select both if you don't care. We will organize the programme so that to maximally fit your preferences.
---

**ORGANISATION COMMITTEE (do not fill out)**

* [x] Editor acknowledgment
* [x] Reviewer 1 
* [ ] Reviewer 2
* [x] Review 1 decision [accept]
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

### CODE REVIEW

**Comment by aliutkus** [comment]
Hi, thanks a lot for the submission
is there somewhere we can see some extended version of the content you're proposing ?

**Comment by giorgiacantisani** [comment]
Yes, sure! Here is the paper: https://hal.telecom-paris.fr/hal-03219350
The code and the demo are available here: https://adasp.telecom-paris.fr/resources/2021-06-01-ugosa-paper/

**Review by aliutkus — COMMENTED** [review]
Interesting topic on how to adapt existing models to new data using user annotations.

I had the chance to already attend your poster on this topic at WASPAA and I'm sure the talk will be great. 

please include a reference to your paper in the submission

**Review by aliutkus — COMMENTED** [review]
would be good if a more detailed summary could be available. In any case, please reference

**Comment by aliutkus** [comment]
Picking accept. Please update asap

**Comment by aliutkus** [comment]
To all participants:
please note that you should update your submission by November 6th 23:00 UTC

Thank you very much

**Comment by giorgiacantisani** [comment]
Thank you for your feedback! I added the reference to the paper, to the demo and code.

**Comment by faroit** [comment]
👏 The submission has been published on midspace (the ISMIR conference platform). The submissions will also be hosted on the workshop website tomorrow. 

The schedule can be seen there or [here](https://docs.google.com/spreadsheets/d/1PaksFcHWUfNPMg-XloA3CJtrvb9uMU0erCFVyvFi9B4/edit?usp=sharing). Please let us know if there is anything missing. Otherwise we see each other on Friday/Saturday!

**Comment by faroit** [comment]
Hi @giorgiacantisani , sorry for the long waiting time but I wasn't able to continue working on the proceedings before. 

I managed to finally work on cutting the video recordings of the workshop and plan to upload the recordings to YouTube very soon. In order to allow me to do this, please acknowledge the following:  

> I hereby authorize the right and permission to copyright and/or publish, reproduce or otherwise use my name, voice, and audio-visual recordings. I acknowledge and understand these materials about or of me may be used for both commercial and/or non-commercial purposes.

> I understand that my image may be edited, copied, exhibited, published and/or distributed. There is no time limit on the validity of this release nor are there any geographic limitations on where these materials may be distributed.

> I authorize that the video will be made available under the [CC BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) on the conference website.

and comment on this by replying with `acknowledge`.

**Comment by giorgiacantisani** [comment]
`acknowledge`

**Comment by giorgiacantisani** [comment]
Thank you for taking care of this! No worries about the delay

**Pull request closed without merging**
