### PR TITLE
[Submission] Rouard and Hadjeres

### PR DESCRIPTION
**Pull request by simonrouard**
Dear mdx workshop committee,

I request a review for the following MDX submission:

### Source Separation using a Score-based Generative Model

Author(s): Simon Rouard and Gaëtan Hadjeres

**Category ***

* [x] `POSTERS` _(+Abstract: 250 Words+one page pdf)_
  > As a participant of the MDX challenge, please know that your poster would be automatically accepted after a minimal prescreening. Hence, don't forget to provide us with the link to your team in the AIcrowd website.
  > You are also welcome to submit us some unrelated abstract, in case your interest would be in presenting some method or idea you would just like to discuss with the participants passing by.  
  > => You *don't* need to include your poster in the PR. Just be ready to have it for D-day and show it to the audience through screen sharing.
* [ ] `LONG TALK`
  > A long talk will last about 20-30min, including questions. This can be about some recent paper you published, or may also present some original research and investigations you did. If you pick this category, please provide us with an extended abstract of the talk, or directly with the slides if you have them available, even in an unfinished state, at your convenience. 
* [ ] `DISCUSSIONS`
  > This category is intended to stimulate fruitful discussions and collaborations. If you pick it, it means you are willing to chair some open discussion with the participants, mainly around one particular aspect of music demixing research. For that purpose, you should provide a minimal abstract as well as a list of a few questions you would like the participants to discuss about. Don't hesitate to propose ideas, We will possibly contact you in case we identify several similar topics that were proposed!

**Preferred Timezone***

* [x] A 11:00 PM (PDT) to 9:00 AM PDT
* [ ] B 11:00 AM (PDT) to 9:00 PM PDT

  > The preferred timezone will help us to organize the day schedule. You should select at least one, but can perfectly select both if you don't care. We will organize the programme so that to maximally fit your preferences.
---

**ORGANISATION COMMITTEE (do not fill out)**

* [x] Editor acknowledgment
* [x] Reviewer 1 
* [ ] Reviewer 2
* [x] Review 1 decision [accept/reject]
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

### CODE REVIEW

**Review by aliutkus — COMMENTED** [review]
reads very interesting. Can't wait to see that

**Comment by aliutkus** [comment]
To all participants:
please note that you should update your submission by November 6th 23:00 UTC

Thank you very much

**Comment by simonrouard** [comment]
I just added our poster, it is a .key file (you need mac os keynote software). Let me know if you can't open it, I will make a pdf version of it but the poster will be static instead of animated.

**Comment by simonrouard** [comment]
@aliutkus I just had an unexpected event (exam at my university) that appeared in my calendar which is during the poster presentation, so I couldn't make it. I am really sorry for this inconvenient situation

**Comment by faroit** [comment]
> @aliutkus I just had an unexpected event (exam at my university) that appeared in my calendar which is during the poster presentation, so I couldn't make it. I am really sorry for this inconvenient situation

that's unfortunate. can you send a little recording that we can play?

**Comment by faroit** [comment]
👏 The submission has been published on midspace (the ISMIR conference platform). The submissions will also be hosted on the workshop website tomorrow. 

The schedule can be seen there or [here](https://docs.google.com/spreadsheets/d/1PaksFcHWUfNPMg-XloA3CJtrvb9uMU0erCFVyvFi9B4/edit?usp=sharing). Please let us know if there is anything missing. Otherwise we see each other on Friday/Saturday!

**Pull request closed without merging**
