### PR TITLE
[Submission] Cogan, Schaffer, Manilow, Pardo

### PR DESCRIPTION
**Pull request by boazcogan**
**Boaz Cogan, Noah Schaffer, Ethan Manilow, Bryan Pardo**

Dear mdx workshop committee,

I request a review for the following MDX submission:

### **Cooking With MSG: Enhancing the Output of Source Separation Using Generative Adversarial Networks**  

**Author(s): Boaz Cogan, Noah Schaffer, Ethan Manilow, Bryan Pardo**  

**Category***

* [x] `POSTERS` _(+Abstract: 250 Words+one page pdf)_
  > As a participant of the MDX challenge, please know that your poster would be automatically accepted after a minimal prescreening. Hence, don't forget to provide us with the link to your team in the AIcrowd website.
  > You are also welcome to submit us some unrelated abstract, in case your interest would be in presenting some method or idea you would just like to discuss with the participants passing by.  
  > => You *don't* need to include your poster in the PR. Just be ready to have it for D-day and show it to the audience through screen sharing.
* [ ] `LONG TALK`
  > A long talk will last about 20-30min, including questions. This can be about some recent paper you published, or may also present some original research and investigations you did. If you pick this category, please provide us with an extended abstract of the talk, or directly with the slides if you have them available, even in an unfinished state, at your convenience. 
* [ ] `DISCUSSIONS`
  > This category is intended to stimulate fruitful discussions and collaborations. If you pick it, it means you are willing to chair some open discussion with the participants, mainly around one particular aspect of music demixing research. For that purpose, you should provide a minimal abstract as well as a list of a few questions you would like the participants to discuss about. Don't hesitate to propose ideas, We will possibly contact you in case we identify several similar topics that were proposed!

**Preferred Timezone***

* [ ] A 11:00 PM (PDT) to 9:00 AM PDT
* [x] B 11:00 AM (PDT) to 9:00 PM PDT

  > The preferred timezone will help us to organize the day schedule. You should select at least one, but can perfectly select both if you don't care. We will organize the programme so that to maximally fit your preferences.
---

**ORGANISATION COMMITTEE (do not fill out)**

* [x] Editor acknowledgment
* [x] Reviewer 1 
* [ ] Reviewer 2
* [x] Review 1 decision [accept
* [ ] Review 2 decision [accept/reject]
* [ ] Editor decision [accept/reject]

### CODE REVIEW

**Review by aliutkus — COMMENTED** [review]
Thanks for the contribution, it reads pretty cool.

1. is there some paper where you already present this work ?
2. if so, please include it in the references

**Comment by boazcogan** [comment]
> Thanks for the contribution, it reads pretty cool.
> 
> 1. is there some paper where you already present this work ?
> 2. if so, please include it in the references

@aliutkus Thanks, we don't have an accompanying paper. One quick note, we had changed the title in the abstract but we missed it in the PR. I've made the update now, I hope this doesn't cause any issues.

**Comment by aliutkus** [comment]
To all participants:
please note that you should update your submission by November 6th 23:00 UTC

Thank you very much

**Comment by faroit** [comment]
@boazcogan also this submission should be nominated for the best title ;-)

**Comment by faroit** [comment]
👏 The submission has been published on midspace (the ISMIR conference platform). The submissions will also be hosted on the workshop website tomorrow. 

The schedule can be seen there or [here](https://docs.google.com/spreadsheets/d/1PaksFcHWUfNPMg-XloA3CJtrvb9uMU0erCFVyvFi9B4/edit?usp=sharing). Please let us know if there is anything missing. Otherwise we see each other on Friday/Saturday!

**Pull request closed without merging**
